# Generated by Django 3.0.5 on 2020-04-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_auto_20200422_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
    ]
